### PR TITLE
resolve paths in more smart fashion

### LINKED ISSUE #172: Failed to load user dict
こんにちは、素晴らしいライブラリをありがとうございます。

ユーザー辞書を登録するため`sudachi.json`をproject rootに配置し、`Dictionary`の`config_path`に`sudachi.json`までのパスを渡した際に以下のエラーが起きます。ユーザー辞書の期待するパスは`/path_to_myproject/dict/user.dic`ですが、実際に参照されるのは`/path_to_myproject/venv/lib/python3.8/site-packages/sudachipy/resources/dict/user.dic`のようです。

ちなみに、`pip install sudachipy`でインストールした場合にこのようなエラーになりますが、`pip install git+git://github.com/WorksApplications/SudachiPy@develop#egg=SudachiPy`の場合エラーは起きませんでした。

```python
from pathlib import Path
from sudachipy import tokenizer
from sudachipy import dictionary

config_path = os.path.join(
    Path(os.path.dirname(__file__)).resolve().parent, "sudachi.json")

tokenizer_obj = dictionary.Dictionary(config_path=config_path).create()

# Exception: Error while constructing dictionary: /path_to_myproject/venv/lib/python3.8/site-packages/sudachipy/resources/dict/user.dic

```

```
// プロジェクト構成
.
├── dict
│   ├── char.def
│   ├── rewrite.def
│   ├── sudachi-user-dict.csv
│   ├── unk.def
│   └── user.dic
├── sudachi.json
└── venv
```

```json

// sudachi.json
{
  "systemDict": "",
  "userDict": ["dict/user.dic"],
  "characterDefinitionFile": "dict/char.def",
  "inputTextPlugin": [
    { "class": "sudachipy.plugin.input_text.DefaultInputTextPlugin" },
    {
      "class": "sudachipy.plugin.input_text.ProlongedSoundMarkInputTextPlugin",
      "prolongedSoundMarks": ["ー", "-", "⁓", "〜", "〰"],
      "replacementSymbol": "ー"
    }
  ],
  "oovProviderPlugin": [
    {
      "class": "sudachipy.plugin.oov.MeCabOovProviderPlugin",
      "charDef": "dict/char.def",
      "unkDef": "dict/unk.def"
    },
    {
      "class": "sudachipy.plugin.oov.SimpleOovProviderPlugin",
      "oovPOS": ["補助記号", "一般", "*", "*", "*", "*"],
      "leftId": 5968,
      "rightId": 5968,
      "cost": 3857
    }
  ],
  "pathRewritePlugin": [
    {
      "class": "sudachipy.plugin.path_rewrite.JoinNumericPlugin",
      "enableNormalize": true
    },
    {
      "class": "sudachipy.plugin.path_rewrite.JoinKatakanaOovPlugin",
      "oovPOS": ["名詞", "普通名詞", "一般", "*", "*", "*"],
      "minLength": 3
    }
  ]
}

```

```
Python: 3.8.10
sudachipy 0.6.2 // pip install sudachipy
sudachipy 0.5.5.dev1+gb244110 // pip install git+
```

## Update

ずっとこのリポジトリのconfig.pyを読んでましたが、v0.6からはこちらの[リポジトリ](https://github.com/WorksApplications/sudachi.rs/blob/develop/sudachi/src/config.rs)ぽいですね。

### PR DESCRIPTION
**Pull request by eiennohito**
Fixes https://github.com/WorksApplications/SudachiPy/issues/172

Sudachi.rs now resolves paths of resources in the following order:
1. Absolute paths stay as they are
2. Relative to "path" value of the config file
3. Relative to "resource_dir" parameter of the config object during creation
4. Relative to the location of the configuration file
5. Relative to the current directory

Also adds `__repr__` to Python Dictionary object which tells which exactly dictionary files are being used.

### CODE REVIEW

File: sudachi/src/config.rs [hunk 1]
```diff
@@ -274,26 +385,28 @@ lazy_static! {
...
     use crate::prelude::SudachiResult;
 
     use super::CURRENT_EXE_DIR;
 
     #[test]
     fn resolve_exe() -> SudachiResult<()> {
         let cfg = Config::new(None, None, None)?;
-        let npath = cfg.resolve_path("$exe/data".to_owned());
+        let npath = cfg.resolve_paths("$exe/data".to_owned());
         let exe_dir: &str = &CURRENT_EXE_DIR;
```
Comment (mh-northlander) [inline sudachi/src/config.rs:385]: Let's check `npath.len() == 1`.

File: sudachi/src/dic/dictionary.rs [hunk 2]
```diff
@@ -86,7 +82,7 @@ impl JapaneseDictionary {
     ) -> SudachiResult<JapaneseDictionary> {
         let mut basic_dict = LoadedDictionary::from_system_dictionary(
             unsafe { storage.system_static_slice() },
-            &cfg.character_definition_file,
+            cfg.complete_path(&cfg.character_definition_file)?.as_path(),
```
Comment (mh-northlander) [inline sudachi/src/dic/dictionary.rs:85]: How about to add `cfg.resolved_character_definition_file()`?

File: sudachi/src/config.rs [hunk 3]
```diff
@@ -207,52 +288,82 @@ impl Config {
...
+        let sdic = sdic.unwrap();
 
-    fn join_if_relative(resource_dir: &PathBuf, file_path: PathBuf) -> PathBuf {
-        if file_path.is_absolute() {
-            file_path
-        } else {
-            resource_dir.join(&file_path)
+        if sdic.is_absolute() {
+            return Ok(sdic.clone());
         }
```
Comment (mh-northlander) [inline sudachi/src/config.rs]: `complete_path(sdic)` seems doing the same check.

File: sudachi/src/config.rs [hunk 4]
```diff
@@ -207,52 +288,82 @@ impl Config {
...
+
+        self.complete_path(sdic)
+    }
+
+    pub fn resolved_user_dicts(&self) -> Result<Vec<PathBuf>, ConfigError> {
```
Comment (mh-northlander) [inline sudachi/src/config.rs:350]: Do we skip CWD case for user_dicts? (Does using `compelete_path` cause problems?)

**Review by mh-northlander — APPROVED** [review]

File: sudachi/src/config.rs (hunk 1 above)
Comment (eiennohito) [reply sudachi/src/config.rs:385]: It's incorrect though (should be 2)

File: sudachi/src/config.rs (hunk 4 above)
Comment (eiennohito) [reply sudachi/src/config.rs:350]: Nope, that's better. Thanks for the suggestion.

File: sudachi/src/config.rs (hunk 3 above)
Comment (eiennohito) [reply sudachi/src/config.rs]: Nice catch!

File: sudachi/src/dic/dictionary.rs (hunk 2 above)
Comment (eiennohito) [reply sudachi/src/dic/dictionary.rs:85]: I think that special methods should focus on dictionary paths and other auxiliary files should use `complete_path`. Also, I want to incorporate character definitions into the new dictionary format.
