### PR TITLE
fix NonBreakChecker

### LINKED ISSUE #79: Fix NonBreakChecker
Sentence splitter originally checked if a morpheme could pass the possible sentence boundary and forbid split on boundaries that could span a morpheme. This check is now not functional

### PR DESCRIPTION
**Pull request by eiennohito**
fixes #79
It does not check can_bow (that check was probably redundant)
and has decreased detection range (~10 characters) from 64 bytes

### CODE REVIEW

File: sudachi/src/sentence_detector.rs [hunk 1]
```diff
@@ -32,22 +32,17 @@ impl<'a> NonBreakChecker<'a> {
...
         for i in lookup_start..eos_byte {
-            // TODO: fixme
-            // if !input.can_bow(i) {
-            //     continue;
-            // }
             for entry in self.lexicon.lookup(input_bytes, i) {
                 let end_byte = entry.end;
-                let char_count = input[i..end_byte].chars().count();
-                if end_byte > eos_byte || (end_byte == eos_byte && char_count > 1) {
+                if end_byte >= eos_byte {
```
Comment (mh-northlander) [inline sudachi/src/sentence_detector.rs]: This needs to be `>`, since words that end at `eos_byte` are not "non-break-word".

I guess the another condition `end_byte == eos_byte && char_count > 1` ([java impl](https://github.com/WorksApplications/Sudachi/blob/9a02c6bbae6338274198deb59d9bdddf0eae328f/src/main/java/com/worksap/nlp/sudachi/JapaneseTokenizer.java#L293)) is to prevent splitting just after words like "モーニング娘。" which end with eos-like char.
It would be better to keep this part too.

**Review by mh-northlander — CHANGES_REQUESTED** [review]

File: sudachi/src/sentence_detector.rs (hunk 1 above)
Comment (eiennohito) [reply sudachi/src/sentence_detector.rs]: Iterating over all characters is also not the best thing to do here. 

I've added the iteration limit and added some comments for the future

**Review by mh-northlander — APPROVED** [review]
